---
title: "About"
format: html
page-layout: full
---

## Education

-   Ph.D. in Psychology, Stockholm University, 2018
-   M.Sc. in Psychology, Stockholm University, 2013
-   B.Sc. in Psychology, Stockholm University, 2011

## Positions

-   Associate Professor (Docent), Stockholm University, 2025–present
-   Senior Lecturer, Stockholm University, 2023-2025
-   Researcher and ICT pedagogue, Stockholm University, 2023
-   Owner and freelance expert in cognitive science and data analysis, Rowboater AB, 2022–present
-   Postdoctoral Researcher, KTH Royal Institute of Technology, 2022–2023
-   Senior Lecturer (temporary), Stockholm University, 2019–2021
-   Ph.D. Student, Stockholm University, 2014–2018

## Other Experience

-   Subject Matter Expert (Science of Learning) for project at The Swedish Ministry of Education, 2023-2024
-   Online learning consultant for KTH Royal Institute of Technology, 2023
-   Organizer of Nordic Learning Analytics Summer Institute (LASI Nordic), 2022
-   Research consultant for research project at Stockholm University, 2019
-   Subject Matter Expert (Memory) for project at The Living History Forum, 2018
-   Research assistant at The Royal Swedish Academy of Sciences, 2011–2014
-   Research assistant at Stockholm University, 2012–2013


## Grants

-   *Rektors medel för kvalitetsutveckling av utbildning*, Stockholm University, 2024
-   Riksbankens Jubileumsfond (P22–0573), 2023–2025
-   Stiftelsen Lars Hiertas Minne, 2014
